### ISSUE TITLE
Leaflet Compatibility

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/glower#3]

**Comment by eknuth** [comment]
+1

**Comment by mourner** [comment]
+1 lol :)

**Comment by tmcw** [comment]
Pull requests accepted :)

**Comment by mourner** [comment]
btw, FYI https://github.com/danzel/Leaflet.utfgrid

**Comment by tmcw** [comment]
Yep, https://github.com/danzel/Leaflet.utfgrid/issues/5

**Comment by jars** [comment]
+1 :+1: -- any plans to implement a Leaflet.js or Mapbox.js adapter?
