### ISSUE TITLE
404 Issues with the demo page

### ISSUE THREAD

**Issue by fnicollet** [cutting-room-floor/glower#7]
Hi,
Just came across the demo page:
http://mapbox.com/glower/#

And everything that is hosted on mapbox (glow.js and the tiles) are all 404. Such as:
http://b.tiles.mapbox.com/v2/energy.billion-ton-update-biomass-production-by-county-v3/5/9/14.png
Returns Tile does not exist
And http://mapbox.com/glower/src/glower.leaf.js is 404

Maybe that's just a CDN issue or something. I'm in France, on my home network, 27 Nov, 23h (GMT+1)

Fabien

**Comment by tmcw** [comment]
Leaflet refs removed in https://github.com/mapbox/glower/commit/a9c16a0696b581e0e3f18aad8987b000e7616798 - the tiles that you're seeing fail are just not rendered.

**Comment by springmeyer** [comment]
To provide a bit more detail: That tile you gave that is a 404 is valid. It is outside the bounds of the sample map. View the tile at OSM and you will see that the tile hits cuba/haiti: http://tile.osm.org/5/9/14.png. The glower sample is not trying to avoid requesting tiles outside of valid bounds, so 404's at the edges are expected (anywhere outside the US: http://tiles.mapbox.com/energy/map/billion-ton-update-biomass-production-by-county-v3)

**Comment by fnicollet** [comment]
ok i had so many 404 in my console i didn't see some were loaded

But the commit about wax doesn't change anything with the 404 JS file i gave in my message

**Comment by springmeyer** [comment]
The 404 JS file was fixed before, in c87c69810e3e7dfa2528070f2e1e025b0ed92269
